# ##### BEGIN MIT LICENSE BLOCK #####
#
# MIT License
#
# Copyright (c) 2023 Steven Garcia
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# ##### END MIT LICENSE BLOCK #####

import struct

from math import degrees
from .format_retail import ScenarioAsset, SALT_SIZE
from mathutils import Vector, Quaternion

DEBUG_PARSER = True
DEBUG_HEADER = True
DEBUG_BODY = True

def process_file(input_stream, tag_format, report):
    TAG = tag_format.TagAsset()
    SCENARIO = ScenarioAsset()

    header_struct = struct.unpack('<hbb32s4sIIIIHbb4s', input_stream.read(64))
    SCENARIO.header = TAG.Header()
    SCENARIO.header.unk1 = header_struct[0]
    SCENARIO.header.flags = header_struct[1]
    SCENARIO.header.type = header_struct[2]
    SCENARIO.header.name = header_struct[3].decode().rstrip('\x00')
    SCENARIO.header.tag_group = header_struct[4].decode().rstrip('\x00')
    SCENARIO.header.checksum = header_struct[5]
    SCENARIO.header.data_offset = header_struct[6]
    SCENARIO.header.data_length = header_struct[7]
    SCENARIO.header.unk2 = header_struct[8]
    SCENARIO.header.version = header_struct[9]
    SCENARIO.header.destination = header_struct[10]
    SCENARIO.header.plugin_handle = header_struct[11]
    SCENARIO.header.engine_tag = header_struct[12].decode().rstrip('\x00')

    if DEBUG_PARSER and DEBUG_HEADER:
        print(" ===== Tag Header ===== ")
        print("Unknown Value: ", SCENARIO.header.unk1)
        print("Flags: ", SCENARIO.header.flags)
        print("Type: ", SCENARIO.header.type)
        print("Name: ", SCENARIO.header.name)
        print("Tag Group: ", SCENARIO.header.tag_group)
        print("Checksum: ", SCENARIO.header.checksum)
        print("Data Offset: ", SCENARIO.header.data_offset)
        print("Data Length:", SCENARIO.header.data_length)
        print("Unknown Value: ", SCENARIO.header.unk2)
        print("Version: ", SCENARIO.header.version)
        print("Destination: ", SCENARIO.header.destination)
        print("Plugin Handle: ", SCENARIO.header.plugin_handle)
        print("Engine Tag: ", SCENARIO.header.engine_tag)
        print(" ")

    level_tag_block_header = struct.unpack('<16x', input_stream.read(16))
    scenario_body_struct = struct.unpack('<4siiIiIIHHiIIfiIIiIIiiIIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiiIIIiiIIIiIIiIIiIIiIIiIIiIIiIIiII4siiI4siiI4siiIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiIIiII', input_stream.read(1032))
    SCENARIO.scenario_body = SCENARIO.ScenarioBody()
    SCENARIO.scenario_body.unused_tag_ref = TAG.TagRef(scenario_body_struct[0].decode('utf-8', 'replace').rstrip('\x00'), "", scenario_body_struct[2] + 1, scenario_body_struct[1], scenario_body_struct[3])
    SCENARIO.scenario_body.skies_tag_block = TAG.TagBlock(scenario_body_struct[4], 0, scenario_body_struct[5], scenario_body_struct[6])
    SCENARIO.scenario_body.scenario_type = scenario_body_struct[7]
    SCENARIO.scenario_body.scenario_flags = scenario_body_struct[8]
    SCENARIO.scenario_body.child_scenarios_tag_block = TAG.TagBlock(scenario_body_struct[9], 0, scenario_body_struct[10], scenario_body_struct[11])
    SCENARIO.scenario_body.local_north = degrees(scenario_body_struct[12])
    SCENARIO.scenario_body.predicted_resources_tag_block = TAG.TagBlock(scenario_body_struct[13], 0, scenario_body_struct[14], scenario_body_struct[15])
    SCENARIO.scenario_body.functions_tag_block = TAG.TagBlock(scenario_body_struct[16], 0, scenario_body_struct[17], scenario_body_struct[18])
    SCENARIO.scenario_body.editor_scenario_data = TAG.RawData(scenario_body_struct[19], scenario_body_struct[20], scenario_body_struct[21], scenario_body_struct[22], scenario_body_struct[23])
    SCENARIO.scenario_body.comments_tag_block = TAG.TagBlock(scenario_body_struct[24], 0, scenario_body_struct[25], scenario_body_struct[26])
    SCENARIO.scenario_body.environment_objects_tag_block = TAG.TagBlock(scenario_body_struct[27], 0, scenario_body_struct[28], scenario_body_struct[29])
    SCENARIO.scenario_body.object_names_tag_block = TAG.TagBlock(scenario_body_struct[30], 0, scenario_body_struct[31], scenario_body_struct[32])
    SCENARIO.scenario_body.scenery_tag_block = TAG.TagBlock(scenario_body_struct[33], 0, scenario_body_struct[34], scenario_body_struct[35])
    SCENARIO.scenario_body.scenery_palette_tag_block = TAG.TagBlock(scenario_body_struct[36], 0, scenario_body_struct[37], scenario_body_struct[38])
    SCENARIO.scenario_body.bipeds_tag_block = TAG.TagBlock(scenario_body_struct[39], 0, scenario_body_struct[40], scenario_body_struct[41])
    SCENARIO.scenario_body.biped_palette_tag_block = TAG.TagBlock(scenario_body_struct[42], 0, scenario_body_struct[43], scenario_body_struct[44])
    SCENARIO.scenario_body.vehicles_tag_block = TAG.TagBlock(scenario_body_struct[45], 0, scenario_body_struct[46], scenario_body_struct[47])
    SCENARIO.scenario_body.vehicle_palette_tag_block = TAG.TagBlock(scenario_body_struct[48], 0, scenario_body_struct[49], scenario_body_struct[50])
    SCENARIO.scenario_body.equipment_tag_block = TAG.TagBlock(scenario_body_struct[51], 0, scenario_body_struct[52], scenario_body_struct[53])
    SCENARIO.scenario_body.equipment_palette_tag_block = TAG.TagBlock(scenario_body_struct[54], 0, scenario_body_struct[55], scenario_body_struct[56])
    SCENARIO.scenario_body.weapons_tag_block = TAG.TagBlock(scenario_body_struct[57], 0, scenario_body_struct[58], scenario_body_struct[59])
    SCENARIO.scenario_body.weapon_palette_tag_block = TAG.TagBlock(scenario_body_struct[60], 0, scenario_body_struct[61], scenario_body_struct[62])
    SCENARIO.scenario_body.device_groups_tag_block = TAG.TagBlock(scenario_body_struct[63], 0, scenario_body_struct[64], scenario_body_struct[65])
    SCENARIO.scenario_body.machines_tag_block = TAG.TagBlock(scenario_body_struct[66], 0, scenario_body_struct[67], scenario_body_struct[68])
    SCENARIO.scenario_body.machine_palette_tag_block = TAG.TagBlock(scenario_body_struct[69], 0, scenario_body_struct[70], scenario_body_struct[71])
    SCENARIO.scenario_body.controls_tag_block = TAG.TagBlock(scenario_body_struct[72], 0, scenario_body_struct[73], scenario_body_struct[74])
    SCENARIO.scenario_body.control_palette_tag_block = TAG.TagBlock(scenario_body_struct[75], 0, scenario_body_struct[76], scenario_body_struct[77])
    SCENARIO.scenario_body.light_fixtures_tag_block = TAG.TagBlock(scenario_body_struct[78], 0, scenario_body_struct[79], scenario_body_struct[80])
    SCENARIO.scenario_body.light_fixtures_palette_tag_block = TAG.TagBlock(scenario_body_struct[81], 0, scenario_body_struct[82], scenario_body_struct[83])
    SCENARIO.scenario_body.sound_scenery_tag_block = TAG.TagBlock(scenario_body_struct[84], 0, scenario_body_struct[85], scenario_body_struct[86])
    SCENARIO.scenario_body.sound_scenery_palette_tag_block = TAG.TagBlock(scenario_body_struct[87], 0, scenario_body_struct[88], scenario_body_struct[89])
    SCENARIO.scenario_body.light_volumes_tag_block = TAG.TagBlock(scenario_body_struct[90], 0, scenario_body_struct[91], scenario_body_struct[92])
    SCENARIO.scenario_body.light_volume_palette_tag_block = TAG.TagBlock(scenario_body_struct[93], 0, scenario_body_struct[94], scenario_body_struct[95])
    SCENARIO.scenario_body.player_starting_profile_tag_block = TAG.TagBlock(scenario_body_struct[96], 0, scenario_body_struct[97], scenario_body_struct[98])
    SCENARIO.scenario_body.player_starting_locations_tag_block = TAG.TagBlock(scenario_body_struct[99], 0, scenario_body_struct[100], scenario_body_struct[101])
    SCENARIO.scenario_body.trigger_volumes_tag_block = TAG.TagBlock(scenario_body_struct[102], 0, scenario_body_struct[103], scenario_body_struct[104])
    SCENARIO.scenario_body.recorded_animations_tag_block = TAG.TagBlock(scenario_body_struct[105], 0, scenario_body_struct[106], scenario_body_struct[107])
    SCENARIO.scenario_body.netgame_flags_tag_block = TAG.TagBlock(scenario_body_struct[108], 0, scenario_body_struct[109], scenario_body_struct[110])
    SCENARIO.scenario_body.netgame_equipment_tag_block = TAG.TagBlock(scenario_body_struct[111], 0, scenario_body_struct[112], scenario_body_struct[113])
    SCENARIO.scenario_body.starting_equipment_tag_block = TAG.TagBlock(scenario_body_struct[114], 0, scenario_body_struct[115], scenario_body_struct[116])
    SCENARIO.scenario_body.bsp_switch_trigger_volumes_tag_block = TAG.TagBlock(scenario_body_struct[117], 0, scenario_body_struct[118], scenario_body_struct[119])
    SCENARIO.scenario_body.decals_tag_block = TAG.TagBlock(scenario_body_struct[120], 0, scenario_body_struct[121], scenario_body_struct[122])
    SCENARIO.scenario_body.decal_palette_tag_block = TAG.TagBlock(scenario_body_struct[123], 0, scenario_body_struct[124], scenario_body_struct[125])
    SCENARIO.scenario_body.detail_object_collection_palette_tag_block = TAG.TagBlock(scenario_body_struct[126], 0, scenario_body_struct[127], scenario_body_struct[128])
    SCENARIO.scenario_body.style_palette_tag_block = TAG.TagBlock(scenario_body_struct[129], 0, scenario_body_struct[130], scenario_body_struct[131])
    SCENARIO.scenario_body.squad_groups_tag_block = TAG.TagBlock(scenario_body_struct[132], 0, scenario_body_struct[133], scenario_body_struct[134])
    SCENARIO.scenario_body.squads_tag_block = TAG.TagBlock(scenario_body_struct[135], 0, scenario_body_struct[136], scenario_body_struct[137])
    SCENARIO.scenario_body.zones_tag_block = TAG.TagBlock(scenario_body_struct[138], 0, scenario_body_struct[139], scenario_body_struct[140])
    SCENARIO.scenario_body.mission_scenes_tag_block = TAG.TagBlock(scenario_body_struct[141], 0, scenario_body_struct[142], scenario_body_struct[143])
    SCENARIO.scenario_body.character_palette_tag_block = TAG.TagBlock(scenario_body_struct[144], 0, scenario_body_struct[145], scenario_body_struct[146])
    SCENARIO.scenario_body.ai_pathfinding_data_tag_block = TAG.TagBlock(scenario_body_struct[147], 0, scenario_body_struct[148], scenario_body_struct[149])
    SCENARIO.scenario_body.ai_animation_references_tag_block = TAG.TagBlock(scenario_body_struct[150], 0, scenario_body_struct[151], scenario_body_struct[152])
    SCENARIO.scenario_body.ai_script_references_tag_block = TAG.TagBlock(scenario_body_struct[153], 0, scenario_body_struct[154], scenario_body_struct[155])
    SCENARIO.scenario_body.ai_recording_references_tag_block = TAG.TagBlock(scenario_body_struct[156], 0, scenario_body_struct[157], scenario_body_struct[158])
    SCENARIO.scenario_body.ai_conversations_tag_block = TAG.TagBlock(scenario_body_struct[159], 0, scenario_body_struct[160], scenario_body_struct[161])
    SCENARIO.scenario_body.script_syntax_data_tag_data = TAG.RawData(scenario_body_struct[162], scenario_body_struct[163], scenario_body_struct[164], scenario_body_struct[165], scenario_body_struct[166])
    SCENARIO.scenario_body.script_string_data_tag_data = TAG.RawData(scenario_body_struct[167], scenario_body_struct[168], scenario_body_struct[169], scenario_body_struct[170], scenario_body_struct[171])
    SCENARIO.scenario_body.scripts_tag_block = TAG.TagBlock(scenario_body_struct[172], 0, scenario_body_struct[173], scenario_body_struct[174])
    SCENARIO.scenario_body.globals_tag_block = TAG.TagBlock(scenario_body_struct[175], 0, scenario_body_struct[176], scenario_body_struct[177])
    SCENARIO.scenario_body.references_tag_block = TAG.TagBlock(scenario_body_struct[178], 0, scenario_body_struct[179], scenario_body_struct[180])
    SCENARIO.scenario_body.source_files_tag_block = TAG.TagBlock(scenario_body_struct[181], 0, scenario_body_struct[182], scenario_body_struct[183])
    SCENARIO.scenario_body.scripting_data_tag_block = TAG.TagBlock(scenario_body_struct[184], 0, scenario_body_struct[185], scenario_body_struct[186])
    SCENARIO.scenario_body.cutscene_flags_tag_block = TAG.TagBlock(scenario_body_struct[187], 0, scenario_body_struct[188], scenario_body_struct[189])
    SCENARIO.scenario_body.cutscene_camera_points_tag_block = TAG.TagBlock(scenario_body_struct[190], 0, scenario_body_struct[191], scenario_body_struct[192])
    SCENARIO.scenario_body.cutscene_titles_tag_block = TAG.TagBlock(scenario_body_struct[193], 0, scenario_body_struct[194], scenario_body_struct[195])
    SCENARIO.scenario_body.custom_object_names_tag_ref = TAG.TagRef(scenario_body_struct[196].decode().rstrip('\x00'), "", scenario_body_struct[198] + 1, scenario_body_struct[197], scenario_body_struct[199])
    SCENARIO.scenario_body.chapter_title_text_tag_ref = TAG.TagRef(scenario_body_struct[200].decode().rstrip('\x00'), "", scenario_body_struct[202] + 1, scenario_body_struct[201], scenario_body_struct[203])
    SCENARIO.scenario_body.hud_messages_tag_ref = TAG.TagRef(scenario_body_struct[204].decode().rstrip('\x00'), "", scenario_body_struct[206] + 1, scenario_body_struct[205], scenario_body_struct[207])
    SCENARIO.scenario_body.structure_bsps_tag_block = TAG.TagBlock(scenario_body_struct[208], 0, scenario_body_struct[209], scenario_body_struct[210])
    SCENARIO.scenario_body.scenario_resources_tag_block = TAG.TagBlock(scenario_body_struct[211], 0, scenario_body_struct[212], scenario_body_struct[213])
    SCENARIO.scenario_body.old_structure_physics_tag_block = TAG.TagBlock(scenario_body_struct[214], 0, scenario_body_struct[215], scenario_body_struct[216])
    SCENARIO.scenario_body.hs_unit_seats_tag_block = TAG.TagBlock(scenario_body_struct[217], 0, scenario_body_struct[218], scenario_body_struct[219])
    SCENARIO.scenario_body.scenario_kill_triggers_tag_block = TAG.TagBlock(scenario_body_struct[220], 0, scenario_body_struct[221], scenario_body_struct[222])
    SCENARIO.scenario_body.hs_syntax_datums_tag_block = TAG.TagBlock(scenario_body_struct[223], 0, scenario_body_struct[224], scenario_body_struct[225])
    SCENARIO.scenario_body.orders_tag_block = TAG.TagBlock(scenario_body_struct[226], 0, scenario_body_struct[227], scenario_body_struct[228])
    SCENARIO.scenario_body.triggers_tag_block = TAG.TagBlock(scenario_body_struct[229], 0, scenario_body_struct[230], scenario_body_struct[231])
    SCENARIO.scenario_body.background_sound_palette_tag_block = TAG.TagBlock(scenario_body_struct[232], 0, scenario_body_struct[233], scenario_body_struct[234])
    SCENARIO.scenario_body.sound_environment_palette_tag_block = TAG.TagBlock(scenario_body_struct[235], 0, scenario_body_struct[236], scenario_body_struct[237])
    SCENARIO.scenario_body.weather_palette_tag_block = TAG.TagBlock(scenario_body_struct[238], 0, scenario_body_struct[239], scenario_body_struct[240])
    SCENARIO.scenario_body.unused_0_tag_block = TAG.TagBlock(scenario_body_struct[241], 0, scenario_body_struct[242], scenario_body_struct[243])
    SCENARIO.scenario_body.unused_1_tag_block = TAG.TagBlock(scenario_body_struct[244], 0, scenario_body_struct[245], scenario_body_struct[246])
    SCENARIO.scenario_body.unused_2_tag_block = TAG.TagBlock(scenario_body_struct[247], 0, scenario_body_struct[248], scenario_body_struct[249])
    SCENARIO.scenario_body.unused_3_tag_block = TAG.TagBlock(scenario_body_struct[250], 0, scenario_body_struct[251], scenario_body_struct[252])
    SCENARIO.scenario_body.scavenger_hunt_objects_tag_block = TAG.TagBlock(scenario_body_struct[253], 0, scenario_body_struct[254], scenario_body_struct[255])
    SCENARIO.scenario_body.scenario_cluster_data_tag_block = TAG.TagBlock(scenario_body_struct[256], 0, scenario_body_struct[257], scenario_body_struct[258])

    SCENARIO.scenario_body.salt_array = []
    for salt_idx in range(SALT_SIZE):
        salt_struct = struct.unpack('<i', input_stream.read(4))
        SCENARIO.scenario_body.salt_array.append(salt_struct[0])

    scenario_body_struct = struct.unpack('<iII4siiIiIIiII4siiIiIIiIIiII4siiIiIIiIIiIIiIIiIIiIIiIIiII4siiI8xiII4siiIiIIiIIiIIiII', input_stream.read(316))
    SCENARIO.scenario_body.spawn_data_tag_block = TAG.TagBlock(scenario_body_struct[0], 0, scenario_body_struct[1], scenario_body_struct[2])
    SCENARIO.scenario_body.sound_effect_collection_tag_ref = TAG.TagRef(scenario_body_struct[3].decode().rstrip('\x00'), "", scenario_body_struct[5] + 1, scenario_body_struct[4], scenario_body_struct[6])
    SCENARIO.scenario_body.crates_tag_block = TAG.TagBlock(scenario_body_struct[7], 0, scenario_body_struct[8], scenario_body_struct[9])
    SCENARIO.scenario_body.crate_palette_tag_block = TAG.TagBlock(scenario_body_struct[10], 0, scenario_body_struct[11], scenario_body_struct[12])
    SCENARIO.scenario_body.global_lighting_tag_ref = TAG.TagRef(scenario_body_struct[13].decode().rstrip('\x00'), "", scenario_body_struct[15] + 1, scenario_body_struct[14], scenario_body_struct[16])
    SCENARIO.scenario_body.atmospheric_fog_palette_tag_block = TAG.TagBlock(scenario_body_struct[17], 0, scenario_body_struct[18], scenario_body_struct[19])
    SCENARIO.scenario_body.planar_fog_palette_tag_block = TAG.TagBlock(scenario_body_struct[20], 0, scenario_body_struct[21], scenario_body_struct[22])
    SCENARIO.scenario_body.flocks_tag_block = TAG.TagBlock(scenario_body_struct[23], 0, scenario_body_struct[24], scenario_body_struct[25])
    SCENARIO.scenario_body.subtitles_tag_ref = TAG.TagRef(scenario_body_struct[26].decode().rstrip('\x00'), "", scenario_body_struct[28] + 1, scenario_body_struct[27], scenario_body_struct[29])
    SCENARIO.scenario_body.decorators_tag_block = TAG.TagBlock(scenario_body_struct[30], 0, scenario_body_struct[31], scenario_body_struct[32])
    SCENARIO.scenario_body.creatures_tag_block = TAG.TagBlock(scenario_body_struct[33], 0, scenario_body_struct[34], scenario_body_struct[35])
    SCENARIO.scenario_body.creature_palette_tag_block = TAG.TagBlock(scenario_body_struct[36], 0, scenario_body_struct[37], scenario_body_struct[38])
    SCENARIO.scenario_body.decorator_palette_tag_block = TAG.TagBlock(scenario_body_struct[39], 0, scenario_body_struct[40], scenario_body_struct[41])
    SCENARIO.scenario_body.bsp_transition_volumes_tag_block = TAG.TagBlock(scenario_body_struct[42], 0, scenario_body_struct[43], scenario_body_struct[44])
    SCENARIO.scenario_body.structure_bsp_lighting_tag_block = TAG.TagBlock(scenario_body_struct[45], 0, scenario_body_struct[46], scenario_body_struct[47])
    SCENARIO.scenario_body.editor_folders_tag_block = TAG.TagBlock(scenario_body_struct[48], 0, scenario_body_struct[49], scenario_body_struct[50])
    SCENARIO.scenario_body.level_data_tag_block = TAG.TagBlock(scenario_body_struct[51], 0, scenario_body_struct[52], scenario_body_struct[53])
    SCENARIO.scenario_body.game_engine_strings_tag_ref = TAG.TagRef(scenario_body_struct[54].decode().rstrip('\x00'), "", scenario_body_struct[56] + 1, scenario_body_struct[55], scenario_body_struct[57])
    SCENARIO.scenario_body.mission_dialogue_tag_block = TAG.TagBlock(scenario_body_struct[58], 0, scenario_body_struct[59], scenario_body_struct[60])
    SCENARIO.scenario_body.objectives_tag_ref = TAG.TagRef(scenario_body_struct[61].decode().rstrip('\x00'), "", scenario_body_struct[63] + 1, scenario_body_struct[62], scenario_body_struct[64])
    SCENARIO.scenario_body.interpolators_tag_block = TAG.TagBlock(scenario_body_struct[65], 0, scenario_body_struct[66], scenario_body_struct[67])
    SCENARIO.scenario_body.shared_references_tag_block = TAG.TagBlock(scenario_body_struct[68], 0, scenario_body_struct[69], scenario_body_struct[70])
    SCENARIO.scenario_body.screen_effect_references_tag_block = TAG.TagBlock(scenario_body_struct[71], 0, scenario_body_struct[72], scenario_body_struct[73])
    SCENARIO.scenario_body.simulation_definition_table_tag_block = TAG.TagBlock(scenario_body_struct[74], 0, scenario_body_struct[75], scenario_body_struct[76])

    if DEBUG_PARSER and DEBUG_BODY:
        print(" ===== SCNR Body ===== ")
        print("Unused Tag Reference Group: ", SCENARIO.scenario_body.unused_tag_ref.tag_group)
        print("Unused Tag Reference Name: ", SCENARIO.scenario_body.unused_tag_ref.name)
        print("Unused Tag Reference Length: ", SCENARIO.scenario_body.unused_tag_ref.name_length)
        print("Unused Tag Reference Salt: ", SCENARIO.scenario_body.unused_tag_ref.salt)
        print("Unused Tag Reference Index: ", SCENARIO.scenario_body.unused_tag_ref.index)
        print("Skies Tag Block Count: ", SCENARIO.scenario_body.skies_tag_block.count)
        print("Skies Tag Block Maximum Count: ", SCENARIO.scenario_body.skies_tag_block.maximum_count)
        print("Skies Tag Block Address: ", SCENARIO.scenario_body.skies_tag_block.address)
        print("Skies Tag Block Definition: ", SCENARIO.scenario_body.skies_tag_block.definition)
        print("Scenario Type: ", SCENARIO.scenario_body.scenario_type)
        print("Scenario Flags: ", SCENARIO.scenario_body.scenario_flags)
        print("Child Scenarios Tag Block Count: ", SCENARIO.scenario_body.child_scenarios_tag_block.count)
        print("Child Scenarios Tag Block Maximum Count: ", SCENARIO.scenario_body.child_scenarios_tag_block.maximum_count)
        print("Child Scenarios Tag Block Address: ", SCENARIO.scenario_body.child_scenarios_tag_block.address)
        print("Child Scenarios Tag Block Definition: ", SCENARIO.scenario_body.child_scenarios_tag_block.definition)
        print("Local North: ", SCENARIO.scenario_body.local_north)
        print("Predicted Resources Tag Block Count: ", SCENARIO.scenario_body.predicted_resources_tag_block.count)
        print("Predicted Resources Tag Block Maximum Count: ", SCENARIO.scenario_body.predicted_resources_tag_block.maximum_count)
        print("Predicted Resources Tag Block Address: ", SCENARIO.scenario_body.predicted_resources_tag_block.address)
        print("Predicted Resources Tag Block Definition: ", SCENARIO.scenario_body.predicted_resources_tag_block.definition)
        print("Functions Tag Block Count: ", SCENARIO.scenario_body.functions_tag_block.count)
        print("Functions Tag Block Maximum Count: ", SCENARIO.scenario_body.functions_tag_block.maximum_count)
        print("Functions Tag Block Address: ", SCENARIO.scenario_body.functions_tag_block.address)
        print("Functions Tag Block Definition: ", SCENARIO.scenario_body.functions_tag_block.definition)
        print("Editor Scenario Data Size: ", SCENARIO.scenario_body.editor_scenario_data.size)
        print("Editor Scenario Data Flags: ", SCENARIO.scenario_body.editor_scenario_data.flags)
        print("Editor Scenario Data Raw Pointer: ", SCENARIO.scenario_body.editor_scenario_data.raw_pointer)
        print("Editor Scenario Data Pointer: ", SCENARIO.scenario_body.editor_scenario_data.pointer)
        print("Editor Scenario Data ID: ", SCENARIO.scenario_body.editor_scenario_data.id)
        print("Comments Tag Block Count: ", SCENARIO.scenario_body.comments_tag_block.count)
        print("Comments Tag Block Maximum Count: ", SCENARIO.scenario_body.comments_tag_block.maximum_count)
        print("Comments Tag Block Address: ", SCENARIO.scenario_body.comments_tag_block.address)
        print("Comments Tag Block Definition: ", SCENARIO.scenario_body.comments_tag_block.definition)
        print("Environment Objects Tag Block Count: ", SCENARIO.scenario_body.environment_objects_tag_block.count)
        print("Environment Objects Tag Block Maximum Count: ", SCENARIO.scenario_body.environment_objects_tag_block.maximum_count)
        print("Environment Objects Tag Block Address: ", SCENARIO.scenario_body.environment_objects_tag_block.address)
        print("Environment Objects Tag Block Definition: ", SCENARIO.scenario_body.environment_objects_tag_block.definition)
        print("Object Names Tag Block Count: ", SCENARIO.scenario_body.object_names_tag_block.count)
        print("Object Names Tag Block Maximum Count: ", SCENARIO.scenario_body.object_names_tag_block.maximum_count)
        print("Object Names Tag Block Address: ", SCENARIO.scenario_body.object_names_tag_block.address)
        print("Object Names Tag Block Definition: ", SCENARIO.scenario_body.object_names_tag_block.definition)
        print("Scenery Tag Block Count: ", SCENARIO.scenario_body.scenery_tag_block.count)
        print("Scenery Tag Block Maximum Count: ", SCENARIO.scenario_body.scenery_tag_block.maximum_count)
        print("Scenery Tag Block Address: ", SCENARIO.scenario_body.scenery_tag_block.address)
        print("Scenery Tag Block Definition: ", SCENARIO.scenario_body.scenery_tag_block.definition)
        print("Scenery Palette Tag Block Count: ", SCENARIO.scenario_body.scenery_palette_tag_block.count)
        print("Scenery Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.scenery_palette_tag_block.maximum_count)
        print("Scenery Palette Tag Block Address: ", SCENARIO.scenario_body.scenery_palette_tag_block.address)
        print("Scenery Palette Tag Block Definition: ", SCENARIO.scenario_body.scenery_palette_tag_block.definition)
        print("Bipeds Tag Block Count: ", SCENARIO.scenario_body.bipeds_tag_block.count)
        print("Bipeds Tag Block Maximum Count: ", SCENARIO.scenario_body.bipeds_tag_block.maximum_count)
        print("Bipeds Tag Block Address: ", SCENARIO.scenario_body.bipeds_tag_block.address)
        print("Bipeds Tag Block Definition: ", SCENARIO.scenario_body.bipeds_tag_block.definition)
        print("Biped Palette Tag Block Count: ", SCENARIO.scenario_body.biped_palette_tag_block.count)
        print("Biped Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.biped_palette_tag_block.maximum_count)
        print("Biped Palette Tag Block Address: ", SCENARIO.scenario_body.biped_palette_tag_block.address)
        print("Biped Palette Tag Block Definition: ", SCENARIO.scenario_body.biped_palette_tag_block.definition)
        print("Vehicles Tag Block Count: ", SCENARIO.scenario_body.vehicles_tag_block.count)
        print("Vehicles Tag Block Maximum Count: ", SCENARIO.scenario_body.vehicles_tag_block.maximum_count)
        print("Vehicles Tag Block Address: ", SCENARIO.scenario_body.vehicles_tag_block.address)
        print("Vehicles Tag Block Definition: ", SCENARIO.scenario_body.vehicles_tag_block.definition)
        print("Vehicle Palette Tag Block Count: ", SCENARIO.scenario_body.vehicle_palette_tag_block.count)
        print("Vehicle Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.vehicle_palette_tag_block.maximum_count)
        print("Vehicle Palette Tag Block Address: ", SCENARIO.scenario_body.vehicle_palette_tag_block.address)
        print("Vehicle Palette Tag Block Definition: ", SCENARIO.scenario_body.vehicle_palette_tag_block.definition)
        print("Equipment Tag Block Count: ", SCENARIO.scenario_body.equipment_tag_block.count)
        print("Equipment Tag Block Maximum Count: ", SCENARIO.scenario_body.equipment_tag_block.maximum_count)
        print("Equipment Tag Block Address: ", SCENARIO.scenario_body.equipment_tag_block.address)
        print("Equipment Tag Block Definition: ", SCENARIO.scenario_body.equipment_tag_block.definition)
        print("Equipment Palette Tag Block Count: ", SCENARIO.scenario_body.equipment_palette_tag_block.count)
        print("Equipment Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.equipment_palette_tag_block.maximum_count)
        print("Equipment Palette Tag Block Address: ", SCENARIO.scenario_body.equipment_palette_tag_block.address)
        print("Equipment Palette Tag Block Definition: ", SCENARIO.scenario_body.equipment_palette_tag_block.definition)
        print("Weapons Tag Block Count: ", SCENARIO.scenario_body.weapons_tag_block.count)
        print("Weapons Tag Block Maximum Count: ", SCENARIO.scenario_body.weapons_tag_block.maximum_count)
        print("Weapons Tag Block Address: ", SCENARIO.scenario_body.weapons_tag_block.address)
        print("Weapons Tag Block Definition: ", SCENARIO.scenario_body.weapons_tag_block.definition)
        print("Weapon Palette Tag Block Count: ", SCENARIO.scenario_body.weapon_palette_tag_block.count)
        print("Weapon Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.weapon_palette_tag_block.maximum_count)
        print("Weapon Palette Tag Block Address: ", SCENARIO.scenario_body.weapon_palette_tag_block.address)
        print("Weapon Palette Tag Block Definition: ", SCENARIO.scenario_body.weapon_palette_tag_block.definition)
        print("Device Group Tag Block Count: ", SCENARIO.scenario_body.device_groups_tag_block.count)
        print("Device Group Tag Block Maximum Count: ", SCENARIO.scenario_body.device_groups_tag_block.maximum_count)
        print("Device Group Tag Block Address: ", SCENARIO.scenario_body.device_groups_tag_block.address)
        print("Device Group Tag Block Definition: ", SCENARIO.scenario_body.device_groups_tag_block.definition)
        print("Machines Tag Block Count: ", SCENARIO.scenario_body.machines_tag_block.count)
        print("Machines Tag Block Maximum Count: ", SCENARIO.scenario_body.machines_tag_block.maximum_count)
        print("Machines Tag Block Address: ", SCENARIO.scenario_body.machines_tag_block.address)
        print("Machines Tag Block Definition: ", SCENARIO.scenario_body.machines_tag_block.definition)
        print("Machine Palette Tag Block Count: ", SCENARIO.scenario_body.machine_palette_tag_block.count)
        print("Machine Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.machine_palette_tag_block.maximum_count)
        print("Machine Palette Tag Block Address: ", SCENARIO.scenario_body.machine_palette_tag_block.address)
        print("Machine Palette Tag Block Definition: ", SCENARIO.scenario_body.machine_palette_tag_block.definition)
        print("Controls Tag Block Count: ", SCENARIO.scenario_body.controls_tag_block.count)
        print("Controls Tag Block Maximum Count: ", SCENARIO.scenario_body.controls_tag_block.maximum_count)
        print("Controls Tag Block Address: ", SCENARIO.scenario_body.controls_tag_block.address)
        print("Controls Tag Block Definition: ", SCENARIO.scenario_body.controls_tag_block.definition)
        print("Control Palette Tag Block Count: ", SCENARIO.scenario_body.control_palette_tag_block.count)
        print("Control Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.control_palette_tag_block.maximum_count)
        print("Control Palette Tag Block Address: ", SCENARIO.scenario_body.control_palette_tag_block.address)
        print("Control Palette Tag Block Definition: ", SCENARIO.scenario_body.control_palette_tag_block.definition)
        print("Light Fixtures Tag Block Count: ", SCENARIO.scenario_body.light_fixtures_tag_block.count)
        print("Light Fixtures Tag Block Maximum Count: ", SCENARIO.scenario_body.light_fixtures_tag_block.maximum_count)
        print("Light Fixtures Tag Block Address: ", SCENARIO.scenario_body.light_fixtures_tag_block.address)
        print("Light Fixtures Tag Block Definition: ", SCENARIO.scenario_body.light_fixtures_tag_block.definition)
        print("Light Fixtures Palette Tag Block Count: ", SCENARIO.scenario_body.light_fixtures_palette_tag_block.count)
        print("Light Fixtures Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.light_fixtures_palette_tag_block.maximum_count)
        print("Light Fixtures Palette Tag Block Address: ", SCENARIO.scenario_body.light_fixtures_palette_tag_block.address)
        print("Light Fixtures Palette Tag Block Definition: ", SCENARIO.scenario_body.light_fixtures_palette_tag_block.definition)
        print("Sound Scenery Tag Block Count: ", SCENARIO.scenario_body.sound_scenery_tag_block.count)
        print("Sound Scenery Tag Block Maximum Count: ", SCENARIO.scenario_body.sound_scenery_tag_block.maximum_count)
        print("Sound Scenery Tag Block Address: ", SCENARIO.scenario_body.sound_scenery_tag_block.address)
        print("Sound Scenery Tag Block Definition: ", SCENARIO.scenario_body.sound_scenery_tag_block.definition)
        print("Sound Scenery Palette Tag Block Count: ", SCENARIO.scenario_body.sound_scenery_palette_tag_block.count)
        print("Sound Scenery Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.sound_scenery_palette_tag_block.maximum_count)
        print("Sound Scenery Palette Tag Block Address: ", SCENARIO.scenario_body.sound_scenery_palette_tag_block.address)
        print("Sound Scenery Palette Tag Block Definition: ", SCENARIO.scenario_body.sound_scenery_palette_tag_block.definition)
        print("Light Volumes Tag Block Count: ", SCENARIO.scenario_body.light_volumes_tag_block.count)
        print("Light Volumes Tag Block Maximum Count: ", SCENARIO.scenario_body.light_volumes_tag_block.maximum_count)
        print("Light Volumes Tag Block Address: ", SCENARIO.scenario_body.light_volumes_tag_block.address)
        print("Light Volumes Tag Block Definition: ", SCENARIO.scenario_body.light_volumes_tag_block.definition)
        print("Light Volume Palette Tag Block Count: ", SCENARIO.scenario_body.light_volume_palette_tag_block.count)
        print("Light Volume Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.light_volume_palette_tag_block.maximum_count)
        print("Light Volume Palette Tag Block Address: ", SCENARIO.scenario_body.light_volume_palette_tag_block.address)
        print("Light Volume Palette Tag Block Definition: ", SCENARIO.scenario_body.light_volume_palette_tag_block.definition)
        print("Player Starting Profile Tag Block Count: ", SCENARIO.scenario_body.player_starting_profile_tag_block.count)
        print("Player Starting Profile Tag Block Maximum Count: ", SCENARIO.scenario_body.player_starting_profile_tag_block.maximum_count)
        print("Player Starting Profile Tag Block Address: ", SCENARIO.scenario_body.player_starting_profile_tag_block.address)
        print("Player Starting Profile Tag Block Definition: ", SCENARIO.scenario_body.player_starting_profile_tag_block.definition)
        print("Player Starting Locations Tag Block Count: ", SCENARIO.scenario_body.player_starting_locations_tag_block.count)
        print("Player Starting Locations Tag Block Maximum Count: ", SCENARIO.scenario_body.player_starting_locations_tag_block.maximum_count)
        print("Player Starting Locations Tag Block Address: ", SCENARIO.scenario_body.player_starting_locations_tag_block.address)
        print("Player Starting Locations Tag Block Definition: ", SCENARIO.scenario_body.player_starting_locations_tag_block.definition)
        print("Trigger Volumes Tag Block Count: ", SCENARIO.scenario_body.trigger_volumes_tag_block.count)
        print("Trigger Volumes Tag Block Maximum Count: ", SCENARIO.scenario_body.trigger_volumes_tag_block.maximum_count)
        print("Trigger Volumes Tag Block Address: ", SCENARIO.scenario_body.trigger_volumes_tag_block.address)
        print("Trigger Volumes Tag Block Definition: ", SCENARIO.scenario_body.trigger_volumes_tag_block.definition)
        print("Recorded Animations Tag Block Count: ", SCENARIO.scenario_body.recorded_animations_tag_block.count)
        print("Recorded Animations Tag Block Maximum Count: ", SCENARIO.scenario_body.recorded_animations_tag_block.maximum_count)
        print("Recorded Animations Tag Block Address: ", SCENARIO.scenario_body.recorded_animations_tag_block.address)
        print("Recorded Animations Tag Block Definition: ", SCENARIO.scenario_body.recorded_animations_tag_block.definition)
        print("Netgame Flags Tag Block Count: ", SCENARIO.scenario_body.netgame_flags_tag_block.count)
        print("Netgame Flags Tag Block Maximum Count: ", SCENARIO.scenario_body.netgame_flags_tag_block.maximum_count)
        print("Netgame Flags Tag Block Address: ", SCENARIO.scenario_body.netgame_flags_tag_block.address)
        print("Netgame Flags Tag Block Definition: ", SCENARIO.scenario_body.netgame_flags_tag_block.definition)
        print("Netgame Equipment Tag Block Count: ", SCENARIO.scenario_body.netgame_equipment_tag_block.count)
        print("Netgame Equipment Tag Block Maximum Count: ", SCENARIO.scenario_body.netgame_equipment_tag_block.maximum_count)
        print("Netgame Equipment Tag Block Address: ", SCENARIO.scenario_body.netgame_equipment_tag_block.address)
        print("Netgame Equipment Tag Block Definition: ", SCENARIO.scenario_body.netgame_equipment_tag_block.definition)
        print("Starting Equipment Tag Block Count: ", SCENARIO.scenario_body.starting_equipment_tag_block.count)
        print("Starting Equipment Tag Block Maximum Count: ", SCENARIO.scenario_body.starting_equipment_tag_block.maximum_count)
        print("Starting Equipment Tag Block Address: ", SCENARIO.scenario_body.starting_equipment_tag_block.address)
        print("Starting Equipment Tag Block Definition: ", SCENARIO.scenario_body.starting_equipment_tag_block.definition)
        print("BSP Switch Trigger Volumes Tag Block Count: ", SCENARIO.scenario_body.bsp_switch_trigger_volumes_tag_block.count)
        print("BSP Switch Trigger Volumes Tag Block Maximum Count: ", SCENARIO.scenario_body.bsp_switch_trigger_volumes_tag_block.maximum_count)
        print("BSP Switch Trigger Volumes Tag Block Address: ", SCENARIO.scenario_body.bsp_switch_trigger_volumes_tag_block.address)
        print("BSP Switch Trigger Volumes Tag Block Definition: ", SCENARIO.scenario_body.bsp_switch_trigger_volumes_tag_block.definition)
        print("Decals Tag Block Count: ", SCENARIO.scenario_body.decals_tag_block.count)
        print("Decals Tag Block Maximum Count: ", SCENARIO.scenario_body.decals_tag_block.maximum_count)
        print("Decals Tag Block Address: ", SCENARIO.scenario_body.decals_tag_block.address)
        print("Decals Tag Block Definition: ", SCENARIO.scenario_body.decals_tag_block.definition)
        print("Decal Palette Tag Block Count: ", SCENARIO.scenario_body.decal_palette_tag_block.count)
        print("Decal Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.decal_palette_tag_block.maximum_count)
        print("Decal Palette Tag Block Address: ", SCENARIO.scenario_body.decal_palette_tag_block.address)
        print("Decal Palette Tag Block Definition: ", SCENARIO.scenario_body.decal_palette_tag_block.definition)
        print("Detail Object Collection Palette Tag Block Count: ", SCENARIO.scenario_body.detail_object_collection_palette_tag_block.count)
        print("Detail Object Collection Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.detail_object_collection_palette_tag_block.maximum_count)
        print("Detail Object Collection Palette Tag Block Address: ", SCENARIO.scenario_body.detail_object_collection_palette_tag_block.address)
        print("Detail Object Collection Palette Tag Block Definition: ", SCENARIO.scenario_body.detail_object_collection_palette_tag_block.definition)
        print("Style Palette Tag Block Count: ", SCENARIO.scenario_body.style_palette_tag_block.count)
        print("Style Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.style_palette_tag_block.maximum_count)
        print("Style Palette Tag Block Address: ", SCENARIO.scenario_body.style_palette_tag_block.address)
        print("Style Palette Tag Block Definition: ", SCENARIO.scenario_body.style_palette_tag_block.definition)
        print("Squad Groups Tag Block Count: ", SCENARIO.scenario_body.squad_groups_tag_block.count)
        print("Squad Groups Tag Block Maximum Count: ", SCENARIO.scenario_body.squad_groups_tag_block.maximum_count)
        print("Squad Groups Tag Block Address: ", SCENARIO.scenario_body.squad_groups_tag_block.address)
        print("Squad Groups Tag Block Definition: ", SCENARIO.scenario_body.squad_groups_tag_block.definition)
        print("Squads Tag Block Count: ", SCENARIO.scenario_body.squads_tag_block.count)
        print("Squads Tag Block Maximum Count: ", SCENARIO.scenario_body.squads_tag_block.maximum_count)
        print("Squads Tag Block Address: ", SCENARIO.scenario_body.squads_tag_block.address)
        print("Squads Tag Block Definition: ", SCENARIO.scenario_body.squads_tag_block.definition)
        print("Zones Tag Block Count: ", SCENARIO.scenario_body.zones_tag_block.count)
        print("Zones Tag Block Maximum Count: ", SCENARIO.scenario_body.zones_tag_block.maximum_count)
        print("Zones Tag Block Address: ", SCENARIO.scenario_body.zones_tag_block.address)
        print("Zones Tag Block Definition: ", SCENARIO.scenario_body.zones_tag_block.definition)
        print("Mission Scenes Tag Block Count: ", SCENARIO.scenario_body.mission_scenes_tag_block.count)
        print("Mission Scenes Tag Block Maximum Count: ", SCENARIO.scenario_body.mission_scenes_tag_block.maximum_count)
        print("Mission Scenes Tag Block Address: ", SCENARIO.scenario_body.mission_scenes_tag_block.address)
        print("Mission Scenes Tag Block Definition: ", SCENARIO.scenario_body.mission_scenes_tag_block.definition)
        print("Character Palette Tag Block Count: ", SCENARIO.scenario_body.character_palette_tag_block.count)
        print("Character Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.character_palette_tag_block.maximum_count)
        print("Character Palette Tag Block Address: ", SCENARIO.scenario_body.character_palette_tag_block.address)
        print("Character Palette Tag Block Definition: ", SCENARIO.scenario_body.character_palette_tag_block.definition)
        print("AI Pathfinding Tag Block Count: ", SCENARIO.scenario_body.ai_pathfinding_data_tag_block.count)
        print("AI Pathfinding Tag Block Maximum Count: ", SCENARIO.scenario_body.ai_pathfinding_data_tag_block.maximum_count)
        print("AI Pathfinding Tag Block Address: ", SCENARIO.scenario_body.ai_pathfinding_data_tag_block.address)
        print("AI Pathfinding Tag Block Definition: ", SCENARIO.scenario_body.ai_pathfinding_data_tag_block.definition)
        print("AI Animation References Tag Block Count: ", SCENARIO.scenario_body.ai_animation_references_tag_block.count)
        print("AI Animation References Tag Block Maximum Count: ", SCENARIO.scenario_body.ai_animation_references_tag_block.maximum_count)
        print("AI Animation References Tag Block Address: ", SCENARIO.scenario_body.ai_animation_references_tag_block.address)
        print("AI Animation References Tag Block Definition: ", SCENARIO.scenario_body.ai_animation_references_tag_block.definition)
        print("AI Script References Tag Block Count: ", SCENARIO.scenario_body.ai_script_references_tag_block.count)
        print("AI Script References Tag Block Maximum Count: ", SCENARIO.scenario_body.ai_script_references_tag_block.maximum_count)
        print("AI Script References Tag Block Address: ", SCENARIO.scenario_body.ai_script_references_tag_block.address)
        print("AI Script References Tag Block Definition: ", SCENARIO.scenario_body.ai_script_references_tag_block.definition)
        print("AI Recording References Tag Block Count: ", SCENARIO.scenario_body.ai_recording_references_tag_block.count)
        print("AI Recording References Tag Block Maximum Count: ", SCENARIO.scenario_body.ai_recording_references_tag_block.maximum_count)
        print("AI Recording References Tag Block Address: ", SCENARIO.scenario_body.ai_recording_references_tag_block.address)
        print("AI Recording References Tag Block Definition: ", SCENARIO.scenario_body.ai_recording_references_tag_block.definition)
        print("AI Conversations Tag Block Count: ", SCENARIO.scenario_body.ai_conversations_tag_block.count)
        print("AI Conversations Tag Block Maximum Count: ", SCENARIO.scenario_body.ai_conversations_tag_block.maximum_count)
        print("AI Conversations Tag Block Address: ", SCENARIO.scenario_body.ai_conversations_tag_block.address)
        print("AI Conversations Tag Block Definition: ", SCENARIO.scenario_body.ai_conversations_tag_block.definition)
        print("Script Syntax Data Size: ", SCENARIO.scenario_body.script_syntax_data_tag_data.size)
        print("Script Syntax Data Flags: ", SCENARIO.scenario_body.script_syntax_data_tag_data.flags)
        print("Script Syntax Data Raw Pointer: ", SCENARIO.scenario_body.script_syntax_data_tag_data.raw_pointer)
        print("Script Syntax Data Pointer: ", SCENARIO.scenario_body.script_syntax_data_tag_data.pointer)
        print("Script Syntax Data ID: ", SCENARIO.scenario_body.script_syntax_data_tag_data.id)
        print("Script String Data Size: ", SCENARIO.scenario_body.script_string_data_tag_data.size)
        print("Script String Data Flags: ", SCENARIO.scenario_body.script_string_data_tag_data.flags)
        print("Script String Data Raw Pointer: ", SCENARIO.scenario_body.script_string_data_tag_data.raw_pointer)
        print("Script String Data Pointer: ", SCENARIO.scenario_body.script_string_data_tag_data.pointer)
        print("Script String Data ID: ", SCENARIO.scenario_body.script_string_data_tag_data.id)
        print("Scripts Tag Block Count: ", SCENARIO.scenario_body.scripts_tag_block.count)
        print("Scripts Tag Block Maximum Count: ", SCENARIO.scenario_body.scripts_tag_block.maximum_count)
        print("Scripts Tag Block Address: ", SCENARIO.scenario_body.scripts_tag_block.address)
        print("Scripts Tag Block Definition: ", SCENARIO.scenario_body.scripts_tag_block.definition)
        print("Globals Tag Block Count: ", SCENARIO.scenario_body.globals_tag_block.count)
        print("Globals Tag Block Maximum Count: ", SCENARIO.scenario_body.globals_tag_block.maximum_count)
        print("Globals Tag Block Address: ", SCENARIO.scenario_body.globals_tag_block.address)
        print("Globals Tag Block Definition: ", SCENARIO.scenario_body.globals_tag_block.definition)
        print("References Tag Block Count: ", SCENARIO.scenario_body.references_tag_block.count)
        print("References Tag Block Maximum Count: ", SCENARIO.scenario_body.references_tag_block.maximum_count)
        print("References Tag Block Address: ", SCENARIO.scenario_body.references_tag_block.address)
        print("References Tag Block Definition: ", SCENARIO.scenario_body.references_tag_block.definition)
        print("Source Files Tag Block Count: ", SCENARIO.scenario_body.source_files_tag_block.count)
        print("Source Files Tag Block Maximum Count: ", SCENARIO.scenario_body.source_files_tag_block.maximum_count)
        print("Source Files Tag Block Address: ", SCENARIO.scenario_body.source_files_tag_block.address)
        print("Source Files Tag Block Definition: ", SCENARIO.scenario_body.source_files_tag_block.definition)
        print("Scripting Data Tag Block Count: ", SCENARIO.scenario_body.scripting_data_tag_block.count)
        print("Scripting Data Tag Block Maximum Count: ", SCENARIO.scenario_body.scripting_data_tag_block.maximum_count)
        print("Scripting Data Tag Block Address: ", SCENARIO.scenario_body.scripting_data_tag_block.address)
        print("Scripting Data Tag Block Definition: ", SCENARIO.scenario_body.scripting_data_tag_block.definition)
        print("Cutscene Flags Tag Block Count: ", SCENARIO.scenario_body.cutscene_flags_tag_block.count)
        print("Cutscene Flags Tag Block Maximum Count: ", SCENARIO.scenario_body.cutscene_flags_tag_block.maximum_count)
        print("Cutscene Flags Tag Block Address: ", SCENARIO.scenario_body.cutscene_flags_tag_block.address)
        print("Cutscene Flags Tag Block Definition: ", SCENARIO.scenario_body.cutscene_flags_tag_block.definition)
        print("Cutscene Camera Points Tag Block Count: ", SCENARIO.scenario_body.cutscene_camera_points_tag_block.count)
        print("Cutscene Camera Points Tag Block Maximum Count: ", SCENARIO.scenario_body.cutscene_camera_points_tag_block.maximum_count)
        print("Cutscene Camera Points Tag Block Address: ", SCENARIO.scenario_body.cutscene_camera_points_tag_block.address)
        print("Cutscene Camera Points Tag Block Definition: ", SCENARIO.scenario_body.cutscene_camera_points_tag_block.definition)
        print("Cutscene Titles Tag Block Count: ", SCENARIO.scenario_body.cutscene_titles_tag_block.count)
        print("Cutscene Titles Tag Block Maximum Count: ", SCENARIO.scenario_body.cutscene_titles_tag_block.maximum_count)
        print("Cutscene Titles Tag Block Address: ", SCENARIO.scenario_body.cutscene_titles_tag_block.address)
        print("Cutscene Titles Tag Block Definition: ", SCENARIO.scenario_body.cutscene_titles_tag_block.definition)
        print("Custom Object Names Tag Reference Group: ", SCENARIO.scenario_body.custom_object_names_tag_ref.tag_group)
        print("Custom Object Names Tag Reference Name: ", SCENARIO.scenario_body.custom_object_names_tag_ref.name)
        print("Custom Object Names Tag Reference Name Length: ", SCENARIO.scenario_body.custom_object_names_tag_ref.name_length)
        print("Custom Object Names Tag Reference Salt: ", SCENARIO.scenario_body.custom_object_names_tag_ref.salt)
        print("Custom Object Names Tag Reference Index: ", SCENARIO.scenario_body.custom_object_names_tag_ref.index)
        print("Chapter Title Text Tag Reference Group: ", SCENARIO.scenario_body.chapter_title_text_tag_ref.tag_group)
        print("Chapter Title Text Tag Reference Name: ", SCENARIO.scenario_body.chapter_title_text_tag_ref.name)
        print("Chapter Title Text Tag Reference Name Length: ", SCENARIO.scenario_body.chapter_title_text_tag_ref.name_length)
        print("Chapter Title Text Tag Reference Salt: ", SCENARIO.scenario_body.chapter_title_text_tag_ref.salt)
        print("Chapter Title Text Tag Reference Index: ", SCENARIO.scenario_body.chapter_title_text_tag_ref.index)
        print("HUD Messages Tag Reference Group: ", SCENARIO.scenario_body.hud_messages_tag_ref.tag_group)
        print("HUD Messages Tag Reference Name: ", SCENARIO.scenario_body.hud_messages_tag_ref.name)
        print("HUD Messages Tag Reference Name Length: ", SCENARIO.scenario_body.hud_messages_tag_ref.name_length)
        print("HUD Messages Tag Reference Salt: ", SCENARIO.scenario_body.hud_messages_tag_ref.salt)
        print("HUD Messages Tag Reference Index: ", SCENARIO.scenario_body.hud_messages_tag_ref.index)
        print("Structure BSP Tag Block Count: ", SCENARIO.scenario_body.structure_bsps_tag_block.count)
        print("Structure BSP Tag Block Maximum Count: ", SCENARIO.scenario_body.structure_bsps_tag_block.maximum_count)
        print("Structure BSP Tag Block Address: ", SCENARIO.scenario_body.structure_bsps_tag_block.address)
        print("Structure BSP Tag Block Definition: ", SCENARIO.scenario_body.structure_bsps_tag_block.definition)
        print("Scenario Resources Tag Block Count: ", SCENARIO.scenario_body.scenario_resources_tag_block.count)
        print("Scenario Resources Tag Block Maximum Count: ", SCENARIO.scenario_body.scenario_resources_tag_block.maximum_count)
        print("Scenario Resources Tag Block Address: ", SCENARIO.scenario_body.scenario_resources_tag_block.address)
        print("Scenario Resources Tag Block Definition: ", SCENARIO.scenario_body.scenario_resources_tag_block.definition)
        print("Old Structure Physics Tag Block Count: ", SCENARIO.scenario_body.old_structure_physics_tag_block.count)
        print("Old Structure Physics Tag Block Maximum Count: ", SCENARIO.scenario_body.old_structure_physics_tag_block.maximum_count)
        print("Old Structure Physics Tag Block Address: ", SCENARIO.scenario_body.old_structure_physics_tag_block.address)
        print("Old Structure Physics Tag Block Definition: ", SCENARIO.scenario_body.old_structure_physics_tag_block.definition)
        print("HS Unit Seats Tag Block Count: ", SCENARIO.scenario_body.hs_unit_seats_tag_block.count)
        print("HS Unit Seats Tag Block Maximum Count: ", SCENARIO.scenario_body.hs_unit_seats_tag_block.maximum_count)
        print("HS Unit Seats Tag Block Address: ", SCENARIO.scenario_body.hs_unit_seats_tag_block.address)
        print("HS Unit Seats Tag Block Definition: ", SCENARIO.scenario_body.hs_unit_seats_tag_block.definition)
        print("Scenario Kill Triggers Tag Block Count: ", SCENARIO.scenario_body.scenario_kill_triggers_tag_block.count)
        print("Scenario Kill Triggers Tag Block Maximum Count: ", SCENARIO.scenario_body.scenario_kill_triggers_tag_block.maximum_count)
        print("Scenario Kill Triggers Tag Block Address: ", SCENARIO.scenario_body.scenario_kill_triggers_tag_block.address)
        print("Scenario Kill Triggers Tag Block Definition: ", SCENARIO.scenario_body.scenario_kill_triggers_tag_block.definition)
        print("HS Syntax Datums Tag Block Count: ", SCENARIO.scenario_body.hs_syntax_datums_tag_block.count)
        print("HS Syntax Datums Tag Block Maximum Count: ", SCENARIO.scenario_body.hs_syntax_datums_tag_block.maximum_count)
        print("HS Syntax Datums Tag Block Address: ", SCENARIO.scenario_body.hs_syntax_datums_tag_block.address)
        print("HS Syntax Datums Tag Block Definition: ", SCENARIO.scenario_body.hs_syntax_datums_tag_block.definition)
        print("Orders Tag Block Count: ", SCENARIO.scenario_body.orders_tag_block.count)
        print("Orders Tag Block Maximum Count: ", SCENARIO.scenario_body.orders_tag_block.maximum_count)
        print("Orders Tag Block Address: ", SCENARIO.scenario_body.orders_tag_block.address)
        print("Orders Tag Block Definition: ", SCENARIO.scenario_body.orders_tag_block.definition)
        print("Triggers Tag Block Count: ", SCENARIO.scenario_body.triggers_tag_block.count)
        print("Triggers Tag Block Maximum Count: ", SCENARIO.scenario_body.triggers_tag_block.maximum_count)
        print("Triggers Tag Block Address: ", SCENARIO.scenario_body.triggers_tag_block.address)
        print("Triggers Tag Block Definition: ", SCENARIO.scenario_body.triggers_tag_block.definition)
        print("Background Sound Palette Tag Block Count: ", SCENARIO.scenario_body.background_sound_palette_tag_block.count)
        print("Background Sound Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.background_sound_palette_tag_block.maximum_count)
        print("Background Sound Palette Tag Block Address: ", SCENARIO.scenario_body.background_sound_palette_tag_block.address)
        print("Background Sound Palette Tag Block Definition: ", SCENARIO.scenario_body.background_sound_palette_tag_block.definition)
        print("Sound Environment Palette Tag Block Count: ", SCENARIO.scenario_body.sound_environment_palette_tag_block.count)
        print("Sound Environment Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.sound_environment_palette_tag_block.maximum_count)
        print("Sound Environment Palette Tag Block Address: ", SCENARIO.scenario_body.sound_environment_palette_tag_block.address)
        print("Sound Environment Palette Tag Block Definition: ", SCENARIO.scenario_body.sound_environment_palette_tag_block.definition)
        print("Weather Palette Tag Block Count: ", SCENARIO.scenario_body.weather_palette_tag_block.count)
        print("Weather Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.weather_palette_tag_block.maximum_count)
        print("Weather Palette Tag Block Address: ", SCENARIO.scenario_body.weather_palette_tag_block.address)
        print("Weather Palette Tag Block Definition: ", SCENARIO.scenario_body.weather_palette_tag_block.definition)
        print("Unused Tag Block Count: ", SCENARIO.scenario_body.unused_0_tag_block.count)
        print("Unused Tag Block Maximum Count: ", SCENARIO.scenario_body.unused_0_tag_block.maximum_count)
        print("Unused Tag Block Address: ", SCENARIO.scenario_body.unused_0_tag_block.address)
        print("Unused Tag Block Definition: ", SCENARIO.scenario_body.unused_0_tag_block.definition)
        print("Unused Tag Block Count: ", SCENARIO.scenario_body.unused_1_tag_block.count)
        print("Unused Tag Block Maximum Count: ", SCENARIO.scenario_body.unused_1_tag_block.maximum_count)
        print("Unused Tag Block Address: ", SCENARIO.scenario_body.unused_1_tag_block.address)
        print("Unused Tag Block Definition: ", SCENARIO.scenario_body.unused_1_tag_block.definition)
        print("Unused Tag Block Count: ", SCENARIO.scenario_body.unused_2_tag_block.count)
        print("Unused Tag Block Maximum Count: ", SCENARIO.scenario_body.unused_2_tag_block.maximum_count)
        print("Unused Tag Block Address: ", SCENARIO.scenario_body.unused_2_tag_block.address)
        print("Unused Tag Block Definition: ", SCENARIO.scenario_body.unused_2_tag_block.definition)
        print("Unused Tag Block Count: ", SCENARIO.scenario_body.unused_3_tag_block.count)
        print("Unused Tag Block Maximum Count: ", SCENARIO.scenario_body.unused_3_tag_block.maximum_count)
        print("Unused Tag Block Address: ", SCENARIO.scenario_body.unused_3_tag_block.address)
        print("Unused Tag Block Definition: ", SCENARIO.scenario_body.unused_3_tag_block.definition)
        print("Scavenger Hunt Objects Tag Block Count: ", SCENARIO.scenario_body.scavenger_hunt_objects_tag_block.count)
        print("Scavenger Hunt Objects Tag Block Maximum Count: ", SCENARIO.scenario_body.scavenger_hunt_objects_tag_block.maximum_count)
        print("Scavenger Hunt Objects Tag Block Address: ", SCENARIO.scenario_body.scavenger_hunt_objects_tag_block.address)
        print("Scavenger Hunt Objects Tag Block Definition: ", SCENARIO.scenario_body.scavenger_hunt_objects_tag_block.definition)
        print("Scenario Cluster Data Tag Block Count: ", SCENARIO.scenario_body.scenario_cluster_data_tag_block.count)
        print("Scenario Cluster Data Tag Block Maximum Count: ", SCENARIO.scenario_body.scenario_cluster_data_tag_block.maximum_count)
        print("Scenario Cluster Data Tag Block Address: ", SCENARIO.scenario_body.scenario_cluster_data_tag_block.address)
        print("Scenario Cluster Data Tag Block Definition: ", SCENARIO.scenario_body.scenario_cluster_data_tag_block.definition)
        for salt_idx, salt in enumerate(SCENARIO.scenario_body.salt_array):
            print("Salt %s: " % salt_idx, salt)

        print("Spawn Data Tag Block Count: ", SCENARIO.scenario_body.spawn_data_tag_block.count)
        print("Spawn Data Tag Block Maximum Count: ", SCENARIO.scenario_body.spawn_data_tag_block.maximum_count)
        print("Spawn Data Tag Block Address: ", SCENARIO.scenario_body.spawn_data_tag_block.address)
        print("Spawn Data Tag Block Definition: ", SCENARIO.scenario_body.spawn_data_tag_block.definition)
        print("Sound Effect Collection Tag Reference Group: ", SCENARIO.scenario_body.sound_effect_collection_tag_ref.tag_group)
        print("Sound Effect Collection Tag Reference Name: ", SCENARIO.scenario_body.sound_effect_collection_tag_ref.name)
        print("Sound Effect Collection Tag Reference Length: ", SCENARIO.scenario_body.sound_effect_collection_tag_ref.name_length)
        print("Sound Effect Collection Tag Reference Salt: ", SCENARIO.scenario_body.sound_effect_collection_tag_ref.salt)
        print("Sound Effect Collection Tag Reference Index: ", SCENARIO.scenario_body.sound_effect_collection_tag_ref.index)
        print("Crates Tag Block Count: ", SCENARIO.scenario_body.crates_tag_block.count)
        print("Crates Tag Block Maximum Count: ", SCENARIO.scenario_body.crates_tag_block.maximum_count)
        print("Crates Tag Block Address: ", SCENARIO.scenario_body.crates_tag_block.address)
        print("Crates Tag Block Definition: ", SCENARIO.scenario_body.crates_tag_block.definition)
        print("Crate Palette Tag Block Count: ", SCENARIO.scenario_body.crate_palette_tag_block.count)
        print("Crate Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.crate_palette_tag_block.maximum_count)
        print("Crate Palette Tag Block Address: ", SCENARIO.scenario_body.crate_palette_tag_block.address)
        print("Crate Palette Tag Block Definition: ", SCENARIO.scenario_body.crate_palette_tag_block.definition)
        print("Global Lighting Tag Reference Group: ", SCENARIO.scenario_body.global_lighting_tag_ref.tag_group)
        print("Global Lighting Tag Reference Name: ", SCENARIO.scenario_body.global_lighting_tag_ref.name)
        print("Global Lighting Tag Reference Length: ", SCENARIO.scenario_body.global_lighting_tag_ref.name_length)
        print("Global Lighting Tag Reference Salt: ", SCENARIO.scenario_body.global_lighting_tag_ref.salt)
        print("Global Lighting Tag Reference Index: ", SCENARIO.scenario_body.global_lighting_tag_ref.index)
        print("Atmospheric Fog Palette Tag Block Count: ", SCENARIO.scenario_body.atmospheric_fog_palette_tag_block.count)
        print("Atmospheric Fog Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.atmospheric_fog_palette_tag_block.maximum_count)
        print("Atmospheric Fog Palette Tag Block Address: ", SCENARIO.scenario_body.atmospheric_fog_palette_tag_block.address)
        print("Atmospheric Fog Palette Tag Block Definition: ", SCENARIO.scenario_body.atmospheric_fog_palette_tag_block.definition)
        print("Planar Fog Palette Tag Block Count: ", SCENARIO.scenario_body.planar_fog_palette_tag_block.count)
        print("Planar Fog Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.planar_fog_palette_tag_block.maximum_count)
        print("Planar Fog Palette Tag Block Address: ", SCENARIO.scenario_body.planar_fog_palette_tag_block.address)
        print("Planar Fog Palette Tag Block Definition: ", SCENARIO.scenario_body.planar_fog_palette_tag_block.definition)
        print("Flocks Tag Block Count: ", SCENARIO.scenario_body.flocks_tag_block.count)
        print("Flocks Tag Block Maximum Count: ", SCENARIO.scenario_body.flocks_tag_block.maximum_count)
        print("Flocks Tag Block Address: ", SCENARIO.scenario_body.flocks_tag_block.address)
        print("Flocks Tag Block Definition: ", SCENARIO.scenario_body.flocks_tag_block.definition)
        print("Subtitles Tag Reference Group: ", SCENARIO.scenario_body.subtitles_tag_ref.tag_group)
        print("Subtitles Tag Reference Name: ", SCENARIO.scenario_body.subtitles_tag_ref.name)
        print("Subtitles Tag Reference Length: ", SCENARIO.scenario_body.subtitles_tag_ref.name_length)
        print("Subtitles Tag Reference Salt: ", SCENARIO.scenario_body.subtitles_tag_ref.salt)
        print("Subtitles Tag Reference Index: ", SCENARIO.scenario_body.subtitles_tag_ref.index)
        print("Decorators Tag Block Count: ", SCENARIO.scenario_body.decorators_tag_block.count)
        print("Decorators Tag Block Maximum Count: ", SCENARIO.scenario_body.decorators_tag_block.maximum_count)
        print("Decorators Tag Block Address: ", SCENARIO.scenario_body.decorators_tag_block.address)
        print("Decorators Tag Block Definition: ", SCENARIO.scenario_body.decorators_tag_block.definition)
        print("Creatures Tag Block Count: ", SCENARIO.scenario_body.creatures_tag_block.count)
        print("Creatures Tag Block Maximum Count: ", SCENARIO.scenario_body.creatures_tag_block.maximum_count)
        print("Creatures Tag Block Address: ", SCENARIO.scenario_body.creatures_tag_block.address)
        print("Creatures Tag Block Definition: ", SCENARIO.scenario_body.creatures_tag_block.definition)
        print("Creature Palette Tag Block Count: ", SCENARIO.scenario_body.creature_palette_tag_block.count)
        print("Creature Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.creature_palette_tag_block.maximum_count)
        print("Creature Palette Tag Block Address: ", SCENARIO.scenario_body.creature_palette_tag_block.address)
        print("Creature Palette Tag Block Definition: ", SCENARIO.scenario_body.creature_palette_tag_block.definition)
        print("Decorator Palette Tag Block Count: ", SCENARIO.scenario_body.decorator_palette_tag_block.count)
        print("Decorator Palette Tag Block Maximum Count: ", SCENARIO.scenario_body.decorator_palette_tag_block.maximum_count)
        print("Decorator Palette Tag Block Address: ", SCENARIO.scenario_body.decorator_palette_tag_block.address)
        print("Decorator Palette Tag Block Definition: ", SCENARIO.scenario_body.decorator_palette_tag_block.definition)
        print("BSP Transition Volumes Tag Block Count: ", SCENARIO.scenario_body.bsp_transition_volumes_tag_block.count)
        print("BSP Transition Volumes Tag Block Maximum Count: ", SCENARIO.scenario_body.bsp_transition_volumes_tag_block.maximum_count)
        print("BSP Transition Volumes Tag Block Address: ", SCENARIO.scenario_body.bsp_transition_volumes_tag_block.address)
        print("BSP Transition Volumes Tag Block Definition: ", SCENARIO.scenario_body.bsp_transition_volumes_tag_block.definition)
        print("Structure BSP Lighting Tag Block Count: ", SCENARIO.scenario_body.structure_bsp_lighting_tag_block.count)
        print("Structure BSP Lighting Tag Block Maximum Count: ", SCENARIO.scenario_body.structure_bsp_lighting_tag_block.maximum_count)
        print("Structure BSP Lighting Tag Block Address: ", SCENARIO.scenario_body.structure_bsp_lighting_tag_block.address)
        print("Structure BSP Lighting Tag Block Definition: ", SCENARIO.scenario_body.structure_bsp_lighting_tag_block.definition)
        print("Editor Folders Tag Block Count: ", SCENARIO.scenario_body.editor_folders_tag_block.count)
        print("Editor Folders Tag Block Maximum Count: ", SCENARIO.scenario_body.editor_folders_tag_block.maximum_count)
        print("Editor Folders Tag Block Address: ", SCENARIO.scenario_body.editor_folders_tag_block.address)
        print("Editor Folders Tag Block Definition: ", SCENARIO.scenario_body.editor_folders_tag_block.definition)
        print("Level Data Tag Block Count: ", SCENARIO.scenario_body.level_data_tag_block.count)
        print("Level Data Tag Block Maximum Count: ", SCENARIO.scenario_body.level_data_tag_block.maximum_count)
        print("Level Data Tag Block Address: ", SCENARIO.scenario_body.level_data_tag_block.address)
        print("Level Data Tag Block Definition: ", SCENARIO.scenario_body.level_data_tag_block.definition)
        print("Game Engine Strings Tag Reference Group: ", SCENARIO.scenario_body.game_engine_strings_tag_ref.tag_group)
        print("Game Engine Strings Tag Reference Name: ", SCENARIO.scenario_body.game_engine_strings_tag_ref.name)
        print("Game Engine Strings Tag Reference Length: ", SCENARIO.scenario_body.game_engine_strings_tag_ref.name_length)
        print("Game Engine Strings Tag Reference Salt: ", SCENARIO.scenario_body.game_engine_strings_tag_ref.salt)
        print("Game Engine Strings Tag Reference Index: ", SCENARIO.scenario_body.game_engine_strings_tag_ref.index)
        print("Mission Dialogue Tag Block Count: ", SCENARIO.scenario_body.mission_dialogue_tag_block.count)
        print("Mission Dialogue Tag Block Maximum Count: ", SCENARIO.scenario_body.mission_dialogue_tag_block.maximum_count)
        print("Mission Dialogue Tag Block Address: ", SCENARIO.scenario_body.mission_dialogue_tag_block.address)
        print("Mission Dialogue Tag Block Definition: ", SCENARIO.scenario_body.mission_dialogue_tag_block.definition)
        print("Objectives Tag Reference Group: ", SCENARIO.scenario_body.objectives_tag_ref.tag_group)
        print("Objectives Tag Reference Name: ", SCENARIO.scenario_body.objectives_tag_ref.name)
        print("Objectives Tag Reference Length: ", SCENARIO.scenario_body.objectives_tag_ref.name_length)
        print("Objectives Tag Reference Salt: ", SCENARIO.scenario_body.objectives_tag_ref.salt)
        print("Objectives Tag Reference Index: ", SCENARIO.scenario_body.objectives_tag_ref.index)
        print("Interpolators Tag Block Count: ", SCENARIO.scenario_body.interpolators_tag_block.count)
        print("Interpolators Tag Block Maximum Count: ", SCENARIO.scenario_body.interpolators_tag_block.maximum_count)
        print("Interpolators Tag Block Address: ", SCENARIO.scenario_body.interpolators_tag_block.address)
        print("Interpolators Tag Block Definition: ", SCENARIO.scenario_body.interpolators_tag_block.definition)
        print("Shared References Tag Block Count: ", SCENARIO.scenario_body.shared_references_tag_block.count)
        print("Shared References Tag Block Maximum Count: ", SCENARIO.scenario_body.shared_references_tag_block.maximum_count)
        print("Shared References Tag Block Address: ", SCENARIO.scenario_body.shared_references_tag_block.address)
        print("Shared References Tag Block Definition: ", SCENARIO.scenario_body.shared_references_tag_block.definition)
        print("Screen Effect References Tag Block Count: ", SCENARIO.scenario_body.screen_effect_references_tag_block.count)
        print("Screen Effect References Tag Block Maximum Count: ", SCENARIO.scenario_body.screen_effect_references_tag_block.maximum_count)
        print("Screen Effect References Tag Block Address: ", SCENARIO.scenario_body.screen_effect_references_tag_block.address)
        print("Screen Effect References Tag Block Definition: ", SCENARIO.scenario_body.screen_effect_references_tag_block.definition)
        print("Simulation Definition Table Tag Block Count: ", SCENARIO.scenario_body.simulation_definition_table_tag_block.count)
        print("Simulation Definition Table Tag Block Maximum Count: ", SCENARIO.scenario_body.simulation_definition_table_tag_block.maximum_count)
        print("Simulation Definition Table Tag Block Address: ", SCENARIO.scenario_body.simulation_definition_table_tag_block.address)
        print("Simulation Definition Table Tag Block Definition: ", SCENARIO.scenario_body.simulation_definition_table_tag_block.definition)
        print(" ")

    current_position = input_stream.tell()
    EOF = input_stream.seek(0, 2)
    if not EOF - current_position == 0: # is something wrong with the parser?
        report({'WARNING'}, "%s elements left after parse end" % (EOF - current_position))

    return SCENARIO
