# ##### BEGIN MIT LICENSE BLOCK #####
#
# MIT License
#
# Copyright (c) 2025 Steven Garcia
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# ##### END MIT LICENSE BLOCK #####

upgrade_functions = {
    "obje": None,
    "devi": None,
    "item": None,
    "unit": None,
    "hlmt": None,
    "mode": None,
    "coll": None,
    "phmo": None,
    "bitm": None,
    "colo": None,
    "unic": None,
    "bipd": None,
    "vehi": None,
    "scen": None,
    "bloc": None,
    "crea": None,
    "phys": None,
    "cont": None,
    "weap": None,
    "ligh": None,
    "effe": None,
    "prt3": None,
    "PRTM": None,
    "pmov": None,
    "matg": None,
    "snd!": None,
    "lsnd": None,
    "eqip": None,
    "ant!": None,
    "MGS2": None,
    "tdtl": None,
    "devo": None,
    "whip": None,
    "BooM": None,
    "trak": None,
    "proj": None,
    "mach": None,
    "ctrl": None,
    "lifi": None,
    "pphy": None,
    "ltmp": None,
    "sbsp": None,
    "scnr": None,
    "shad": None,
    "stem": None,
    "slit": None,
    "spas": None,
    "vrtx": None,
    "pixl": None,
    "DECR": None,
    "sky ": None,
    "wind": None,
    "snde": None,
    "lens": None,
    "fog ": None,
    "fpch": None,
    "metr": None,
    "deca": None,
    "coln": None,
    "jpt!": None,
    "udlg": None,
    "itmc": None,
    "vehc": None,
    "wphi": None,
    "grhi": None,
    "unhi": None,
    "nhdt": None,
    "hud#": None,
    "hudg": None,
    "mply": None,
    "dobc": None,
    "ssce": None,
    "hmt ": None,
    "wgit": None,
    "skin": None,
    "wgtz": None,
    "wigl": None,
    "sily": None,
    "goof": None,
    "foot": None,
    "garb": None,
    "styl": None,
    "char": None,
    "adlg": None,
    "mdlg": None,
    "*cen": None,
    "*ipd": None,
    "*ehi": None,
    "*qip": None,
    "*eap": None,
    "*sce": None,
    "*igh": None,
    "dgr*": None,
    "dec*": None,
    "cin*": None,
    "trg*": None,
    "clu*": None,
    "*rea": None,
    "dc*s": None,
    "sslt": None,
    "hsc*": None,
    "ai**": None,
    "/**/": None,
    "bsdt": None,
    "mpdt": None,
    "sncl": None,
    "mulg": None,
    "<fx>": None,
    "sfx+": None,
    "gldf": None,
    "jmad": None,
    "clwd": None,
    "egor": None,
    "weat": None,
    "snmx": None,
    "spk!": None,
    "ugh!": None,
    "$#!+": None,
    "mcsr": None,
    "tag+": None,
}
